### ISSUE TITLE
‘char_path’には何を与えますか

### ISSUE THREAD

**Issue by shimaken-git** [Hiroshiba/hihobot#1]
すばらしいアイディアなので試してみようと思ってソース見てるんですが、chars_pathってのは何を与えればいいんですか？
また、config(特にネット情報)の例を教えてもらえないでしょうか。

ご教授のほどよろしくお願いします。

**Comment by Hiroshiba** [comment]
`chars_path`は、 https://github.com/Hiroshiba/hihobot/blob/f970dfc4e85c6fd81439e6020b744fdf7ee37329/pre_process.py で得られた`chars`のjson listファイルのパスを想定しています。
`chars`はＮ種類の文字のリストで、頻出文字Ｎつです。日本語だとN=2048でそれなりの精度が得られました。

configは適したパラメータを探索している段階です。とりあえず試したのは、２５６チャンネルの２層ＬＳＴＭです。
１０万文章程度だとかなり過学習しますが、それなりに面白い会話応答をしてくれることを確かめました。

issueは一旦閉じますが、また似たような質問があればopenして聞いてください。
