### ISSUE TITLE
make_datasetを実行したときにエラー

### ISSUE THREAD

**Issue by yuuSiVo** [Hiroshiba/hihobot#2]
make_dataset.pyを実行したときに、

  File "make_dataset.py", line 20
    def make_dataset(
SyntaxError: duplicate argument 'Path' in function definition

というエラーがでます。この対処法を教えてください。

環境はPython3.5, bash on ubuntuです

**Comment by Hiroshiba** [comment]
型アノテーションに失敗しているのかもしれません。
python3.6にしたら出ないかもしれません。

もしくは、
```
        texts_path: Path,
```
となっている部分を
```
        texts_path,
```
とすると、エラーが出ないようになると思います。

**Comment by Hiroshiba** [comment]
issueは一度closeしますが、同様の問題が生じた場合は再度openしてください。
